server:
  port: 8081

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: true
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
#    url: jdbc:mysql://localhost:3306/uaac?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://127.0.0.1:3306/uaac?useUnicode=true&charaterEncoding=utf-8&serverTimezone=UTC&useSSL=false

    username: root
    password: yuyang
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  before: true
  not-empty: false
  identity: MYSQL
pagehelper:
  offset-as-page-num: true
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
siorrrbei:
  fastjson:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always