server:
  port: 50000
spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        min-idle: 0
        max-idle: 2
        max-wait: 10000ms
        max-active: 2
        time-between-eviction-runs: 10000
  security:
    oauth2:
      jwt:
        signingKey: test_key
  application:
    name: siorrrbei-oauth2
  datasource:
    url: jdbc:mysql://localhost:3306/uaac?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yuyang
  cloud:
    # 使用 Nacos 作为服务注册发现
    nacos:
      discovery:
        server-addr: 172.20.106.131:8848
  jpa:
    open-in-view: false
    show-sql: true
logging:
  level:
    com.mic.oauth2: debug
